### ISSUE TITLE
GGST calculators don't take gatlings into account

### ISSUE THREAD

**Issue by Xroud** [D4RKONION/FAT#42]
Most calculations end up being incorrect because gatlings are not accounted for.
Example: Frame Trap Checker with cS->fS combo input will say there is an 11 frame gap despite the 2 moves linking into each other in game thanks to the gatling system cancelling the endlag of the first move.
Currently:
![image](https://user-images.githubusercontent.com/24396496/130151495-81aedf06-3023-4491-bc48-fbddb18a170b.png)
Expected:
![image](https://user-images.githubusercontent.com/24396496/130151959-238cb8f0-7bac-4d1f-8729-604447fb9a0b.png)
 ("gatling bonus" represents the extra frames gained by cancelling the recovery frames with a gatling move)

**Comment by D4RKONION** [comment]
Hi there!

First off, as was explained in the discord by Jojo, the calculations aren't incorrect given that the app is checking for links. It's just that links don't happen often in the context of a game like Guilty Gear. 

In order to account for the moves being gattling-ed into each other, that would need to happen on the "cancel" tab, as the "link" tab is doing exactly what it is expected to at th moment. As for how it would be implemented on the cancel tab, I don't know if there is a universal bit of maths that can do the hard work here or if different moves cancel on different unique frames.

If there's some universal maths that you can do, assuming that a move is cancelled on the first possible frame, go for it. If it's unique to each move which active/recovery frame can be cancelled from, the fix would also need to happen at the spreadsheet level which is an immense amount of work and a WNF.

**Comment by D4RKONION** [comment]
WNF
